"""User-facing response builders for Humility denials and reframes."""
from __future__ import annotations

from typing import Sequence

from humility.rules import HARD_DENY_REASONS, REFRAMABLE_REASONS


def _categorize(reasons: Sequence[str]) -> set[str]:
    categories: set[str] = set()
    for reason in reasons:
        for key, cat in HARD_DENY_REASONS.items():
            if key in reason:
                categories.add(cat)
        for key, cat in REFRAMABLE_REASONS.items():
            if key in reason:
                categories.add(cat)
    return categories


def compassionate_response(reasons: Sequence[str]) -> str:
    """Build a user-facing explanation for a hard denial.

    Never leaves the user stranded — always offers next steps.
    """
    categories = _categorize(reasons)
    parts = [
        "I want to help you with this, and I appreciate you reaching out. "
        "However, this topic requires careful handling that goes beyond what "
        "I can provide with full confidence as an AI system."
    ]

    if "metaphysical" in categories:
        parts.append(
            "\n\n**Why I'm limited here:** Your request involves philosophical or "
            "metaphysical framing that could lead me to make claims beyond my "
            "capabilities. I'm designed to be transparent about this limitation."
        )
    elif "authority_claim" in categories or "persuasion" in categories:
        parts.append(
            "\n\n**Why I'm limited here:** A pattern was detected that could lead "
            "to authoritative claims or one-sided framing. I'm designed to "
            "present balanced, humble perspectives."
        )
    elif "uncertainty" in categories or "human_consensus" in categories:
        parts.append(
            "\n\n**Why I'm stepping back:** This appears to be a high-impact "
            "topic where my uncertainty is too high to provide responsible "
            "guidance without human expert verification."
        )
    elif "domain_boundary" in categories:
        parts.append(
            "\n\n**Why I'm stepping back:** This question extends beyond my "
            "validated knowledge domain. I'd rather be honest about that than "
            "risk giving you inaccurate information."
        )

    parts.append(
        "\n\n**What you can do:**\n"
        "- Rephrase your question with more specific context\n"
        "- Ask about related topics I can help with confidently\n"
        "- Consult a qualified human expert for this decision"
    )
    parts.append(
        "\n\n*Response generated by the Humility guardrail (SAIVAS framework).*"
    )
    return "".join(parts)


def reframe_instructions(reasons: Sequence[str]) -> str | None:
    """Build system-level reframing guidance for soft-deny reasons.

    Returns None if no reframable reasons are present.
    """
    categories = _categorize(reasons)
    instructions: list[str] = []

    if "uncertainty" in categories:
        instructions.append(
            "IMPORTANT: Your response involves a high-impact topic. You MUST "
            "explicitly acknowledge uncertainty and limitations. Use phrases "
            "like 'based on available information', 'I recommend consulting a "
            "professional', or 'this should be verified by a qualified human "
            "expert'."
        )
    if "human_consensus" in categories:
        instructions.append(
            "IMPORTANT: This topic involves restricted or sensitive information. "
            "Frame your response as informational guidance only and explicitly "
            "recommend human expert review before any action is taken."
        )
    if "domain_boundary" in categories:
        instructions.append(
            "IMPORTANT: This question may extend beyond your validated "
            "knowledge. Clearly state the boundaries of your knowledge and "
            "recommend authoritative sources for verification."
        )

    return "\n\n".join(instructions) if instructions else None
